# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' One-hot encodes a DNA base
#'
#' @param base A,T,C,G or N
#' @return A one-hot encoded vector
encode_base <- function(base) {
    .Call(`_XalBio_encode_base`, base)
}

#' One-hot encodes a DNA sequence
#'
#' @param DNA sequence of A,T,C,G or N bases
#' @return A one-hot encoded vector
encode_sequence <- function(sequence) {
    .Call(`_XalBio_encode_sequence`, sequence)
}

#' Generates reverse-compliment of DNA sequence
#'
#' @param DNA sequence of A,T,C,G or N bases
#' @return Reverse-compliment of sequence
reverse_compliment <- function(sequence) {
    .Call(`_XalBio_reverse_compliment`, sequence)
}

